### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vnphanquang** [hungtruong97/pcg-backend#1]
A couple of feedbacks regarding the current code

## Clean up

There are several files not used:

- `html.txt`
- `analytics.js`: looks like you tested the API with this, and it should live in the CLI app repo. Remove here
- `DS_Store` is a metadata file generated by macos, and generally not needed for our purposes. Delete them, and add to `.gitignore`.

### Invoke from backend

For better security, the backend should mask user's info and should not let the client do that. Imagine if some hacker intercept your network response, or simply open the network tab in devtool, they will be able to see the naked emails & names.

### Implementation

- Remove the `maskInfo("Hung Truong");` and the end of the file
- Adjust the `jsdocs` to remove the `i` param
- Consistent naming, ~~`LastCharacterBeforeAt`~~ should be lower-case, i.e `lastCharacterBeforeAt`

This `maskInfo` currently handles both name and email; users of this function wouldn't know that without reading the implementation code. Make a habbit of  documenting your code, for yourself first and others. For example:

```javascript
/**
 * Mask name or email string by replacing certain segments with *
 * 
 * @param {string} nameOrEmail 
 */
function maskInfo(nameOrEmail) {}
```

This helps the code easier to use and maintain. Intellisense (editor autocompletion) can also pick up this documentation upon hover.

## About HTTP Status Code

The current `POST /pcg` API endpoint returns a 201 status code upon success. This is totally fine. But beware of the meaning of each status code. `201` often means a **new** resource has been created. In our case, that might not necessarily the case, i.e if we are updating the record, no **new** resource is created.

On the other hand, people will also use `PUT` or `PATCH` HTTP methods explicitly for updating a resource, and `POST` only for "creation".

These are only conventions that you should know about. Refer to MDN docs on [HTTP Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) and [HTTP Status Code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) for more information.

**Comment by hungtruong97** [comment]
fixed all @vnphanquang
